url: "https://annikatjuka.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
title: "Dr. Annika Tjuka" # the name of your site, e.g. ACME Corp.
description: "Language Scientist"
